#!/usr/bin/env python3
"""Pack the authored 24px RGBA life icon into native BGR555 renderer data."""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
image = Image.open(root / 'assets/zero/life-head.png').convert('RGBA')
if image.size != (24, 24):
    raise SystemExit('Zero life icon must be 24x24')
rows = []
for y in range(24):
    values = []
    for x in range(24):
        r, g, b, a = image.getpixel((x, y))
        color = 0x8000 if a < 128 else (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)
        values.append(f'0x{color:04x}')
    rows.append('  {' + ','.join(values) + '},')
(root / 'src/mmx_zero_life.h').write_text(
    '/* Generated by tools/compile_zero_life.py from assets/zero/life-head.png. */\n'
    'static const uint16_t zero_life_pixels[24][24] = {\n' + '\n'.join(rows) + '\n};\n',
    encoding='utf-8', newline='\n')
