#!/usr/bin/env python3
"""Pack the authored 17x16 RGBA life icon into native BGR555 renderer data."""
from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[1]
image = Image.open(root / 'assets/zero/life-head.png').convert('RGBA')
if image.size != (17, 16):
    raise SystemExit('Zero life icon must be 17x16')
rows = []
for y in range(image.height):
    values = []
    for x in range(image.width):
        r, g, b, a = image.getpixel((x, y))
        color = 0x8000 if a < 128 else (r >> 3) | ((g >> 3) << 5) | ((b >> 3) << 10)
        values.append(f'0x{color:04x}')
    rows.append('  {' + ','.join(values) + '},')
(root / 'src/mmx_zero_life.h').write_text(
    '/* Generated by tools/compile_zero_life.py from assets/zero/life-head.png. */\n'
    'static const uint16_t zero_life_pixels[MMX_ZERO_LIFE_HEIGHT][MMX_ZERO_LIFE_WIDTH] = {\n' + '\n'.join(rows) + '\n};\n',
    encoding='utf-8', newline='\n')
